apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: aras-demo-pod-kill
  namespace: default
spec:
  action: pod-kill
  mode: one
  selector:
    namespaces:
    - default
    labelSelectors:
      app: aras-demo
  duration: "30s"
